/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create-group`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notification-settings`; params?: Router.UnknownInputParams; } | { pathname: `/record-video`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/video-call`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reels` | `/reels`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit-username`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/security/lock`; params?: Router.UnknownInputParams; } | { pathname: `/security/setup-pin`; params?: Router.UnknownInputParams; } | { pathname: `/chat/[contactId]`, params: Router.UnknownInputParams & { contactId: string | number; } } | { pathname: `/group/[groupId]`, params: Router.UnknownInputParams & { groupId: string | number; } } | { pathname: `/group-manage/[manageId]`, params: Router.UnknownInputParams & { manageId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/create-group`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/notification-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/record-video`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/video-call`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reels` | `/reels`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/edit-username`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/security/lock`; params?: Router.UnknownOutputParams; } | { pathname: `/security/setup-pin`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/[contactId]`, params: Router.UnknownOutputParams & { contactId: string; } } | { pathname: `/group/[groupId]`, params: Router.UnknownOutputParams & { groupId: string; } } | { pathname: `/group-manage/[manageId]`, params: Router.UnknownOutputParams & { manageId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/create-group${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/notification-settings${`?${string}` | `#${string}` | ''}` | `/record-video${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/video-call${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reels${`?${string}` | `#${string}` | ''}` | `/reels${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/profile/edit-username${`?${string}` | `#${string}` | ''}` | `/profile/edit${`?${string}` | `#${string}` | ''}` | `/security/lock${`?${string}` | `#${string}` | ''}` | `/security/setup-pin${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create-group`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notification-settings`; params?: Router.UnknownInputParams; } | { pathname: `/record-video`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/video-call`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reels` | `/reels`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit-username`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/security/lock`; params?: Router.UnknownInputParams; } | { pathname: `/security/setup-pin`; params?: Router.UnknownInputParams; } | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/group/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/group-manage/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/chat/[contactId]`, params: Router.UnknownInputParams & { contactId: string | number; } } | { pathname: `/group/[groupId]`, params: Router.UnknownInputParams & { groupId: string | number; } } | { pathname: `/group-manage/[manageId]`, params: Router.UnknownInputParams & { manageId: string | number; } };
    }
  }
}
